In [6]:
%pip install tensorflow-gpu

In [0]:
import tensorflow as tf
import numpy as np
import os 
import time

In [0]:
file_dat=tf.keras.utils.get_file('shakespeare.txt', 'https://storage.googleapis.com/download.tensorflow.org/data/shakespeare.txt')

In [0]:
text=open(file_dat,'rb').read()

text=text.decode(encoding='utf-8')

In [10]:
print("No. of characters in the text ",len(text))

No. of characters in the text  1115394


In [11]:
print(text[:100])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You


In [0]:
vocab=sorted(set(text))

In [13]:
print(vocab)

['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [14]:
print("Length of characters in vocabulary ",len(vocab))

Length of characters in vocabulary  65


In [15]:
#Let's enumerate or vectorize the characters 

mapping={v:u for u,v in enumerate(vocab) }
print(mapping)

{'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 37, 'Z': 38, 'a': 39, 'b': 40, 'c': 41, 'd': 42, 'e': 43, 'f': 44, 'g': 45, 'h': 46, 'i': 47, 'j': 48, 'k': 49, 'l': 50, 'm': 51, 'n': 52, 'o': 53, 'p': 54, 'q': 55, 'r': 56, 's': 57, 't': 58, 'u': 59, 'v': 60, 'w': 61, 'x': 62, 'y': 63, 'z': 64}


In [16]:
char_arr=np.array(vocab)
print(char_arr)

['\n' ' ' '!' '$' '&' "'" ',' '-' '.' '3' ':' ';' '?' 'A' 'B' 'C' 'D' 'E'
 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R' 'S' 'T' 'U' 'V' 'W'
 'X' 'Y' 'Z' 'a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o'
 'p' 'q' 'r' 's' 't' 'u' 'v' 'w' 'x' 'y' 'z']


In [17]:
#Let's see how our encoded text would look like with first 250 chars

text_as_int=np.array([mapping[each] for each in text])
print(text_as_int)

[18 47 56 ... 45  8  0]


In [0]:
#let's convert text to tensor slices

sequence_len=100
ex_per_epoch=len(text)//(sequence_len+1)

char_ds=tf.data.Dataset.from_tensor_slices(text_as_int)

In [0]:
sequences=char_ds.batch(sequence_len+1,drop_remainder=True)

In [0]:
def split_input_target(chunk):
    input_text = chunk[:-1]
    target_text = chunk[1:]
    return input_text, target_text

dataset = sequences.map(split_input_target)

In [33]:
print(dataset)

<MapDataset shapes: ((100,), (100,)), types: (tf.int64, tf.int64)>


In [34]:
for each in dataset.take(2):
  print(each)

(<tf.Tensor: id=617, shape=(100,), dtype=int64, numpy=
array([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43,
       44, 53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39,
       52, 63,  1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1,
       51, 43,  1, 57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31,
       54, 43, 39, 49,  6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56,
       57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 37, 53, 59])>, <tf.Tensor: id=618, shape=(100,), dtype=int64, numpy=
array([47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
       53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52,
       63,  1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51,
       43,  1, 57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54,
       43, 39, 49,  6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57,
       58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1])>)
(

In [35]:
for input_example, target_example in  dataset.take(1):
  print ('Input data ',repr(''.join(char_arr[input_example.numpy()])))
  print ('Output data ',repr(''.join(char_arr[target_example.numpy()])))

Input data  'First Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou'
Output data  'irst Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou '


In [36]:
BATCH_SIZE = 64

# Buffer size to shuffle the dataset
# (TF data is designed to work with possibly infinite sequences,
# so it doesn't attempt to shuffle the entire sequence in memory. Instead,
# it maintains a buffer in which it shuffles elements).
BUFFER_SIZE = 10000

dataset = dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE, drop_remainder=True)

dataset

<BatchDataset shapes: ((64, 100), (64, 100)), types: (tf.int64, tf.int64)>

In [0]:
# Length of the vocabulary in chars
vocab_size = len(vocab)

# The embedding dimension
embedding_dim = 256

# Number of RNN units
rnn_units = 1024

In [0]:
def build_model(vocab_size, embedding_dim, rnn_units, batch_size):
  model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim,
                              batch_input_shape=[batch_size, None]),
    tf.keras.layers.GRU(rnn_units,
                        return_sequences=True,
                        stateful=True,
                        recurrent_initializer='glorot_uniform'),
    tf.keras.layers.Dense(vocab_size)
  ])
  return model

In [0]:
model = build_model(
  vocab_size = len(vocab),
  embedding_dim=embedding_dim,
  rnn_units=rnn_units,
  batch_size=BATCH_SIZE)

In [40]:
for input_example_batch, target_example_batch in dataset.take(1):
  example_batch_predictions = model(input_example_batch)
  print(example_batch_predictions.shape, "# (batch_size, sequence_length, vocab_size)")

(64, 100, 65) # (batch_size, sequence_length, vocab_size)


In [41]:
def loss(labels, logits):
  return tf.keras.losses.sparse_categorical_crossentropy(labels, logits, from_logits=True)

example_batch_loss  = loss(target_example_batch, example_batch_predictions)
print("Prediction shape: ", example_batch_predictions.shape, " # (batch_size, sequence_length, vocab_size)")
print("scalar_loss:      ", example_batch_loss.numpy().mean())

Prediction shape:  (64, 100, 65)  # (batch_size, sequence_length, vocab_size)
scalar_loss:       4.175845


In [0]:
model.compile(optimizer='adam', loss=loss)

In [0]:
checkpoint_dir="chkpts"
check_point_pref=os.path.join(checkpoint_dir,'chkpts_{epoch}')

checkpoint_callback=tf.keras.callbacks.ModelCheckpoint(filepath=check_point_pref,save_weights_only=True)

In [45]:
EPOCHS=10
history = model.fit(dataset, epochs=EPOCHS,callbacks=[checkpoint_callback])

Epoch 1/10
172/172 [==============================] - 24s 140ms/step - loss: 1.2151
Epoch 2/10
172/172 [==============================] - 24s 140ms/step - loss: 1.1846
Epoch 3/10
172/172 [==============================] - 24s 140ms/step - loss: 1.1514
Epoch 4/10
172/172 [==============================] - 24s 141ms/step - loss: 1.1177
Epoch 5/10
172/172 [==============================] - 24s 141ms/step - loss: 1.0834
Epoch 6/10
172/172 [==============================] - 24s 141ms/step - loss: 1.0484
Epoch 7/10
172/172 [==============================] - 24s 141ms/step - loss: 1.0134
Epoch 8/10
172/172 [==============================] - 24s 142ms/step - loss: 0.9779
Epoch 9/10
172/172 [==============================] - 24s 141ms/step - loss: 0.9421
Epoch 10/10
172/172 [==============================] - 24s 141ms/step - loss: 0.9085


In [46]:
tf.train.latest_checkpoint(checkpoint_dir)

'chkpts/chkpts_10'

In [0]:
model = build_model(vocab_size, embedding_dim, rnn_units, batch_size=1)

model.load_weights(tf.train.latest_checkpoint(checkpoint_dir))

model.build(tf.TensorShape([1, None]))

In [48]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (1, None, 256)            16640     
_________________________________________________________________
gru_2 (GRU)                  (1, None, 1024)           3938304   
_________________________________________________________________
dense_2 (Dense)              (1, None, 65)             66625     
Total params: 4,021,569
Trainable params: 4,021,569
Non-trainable params: 0
_________________________________________________________________


In [0]:
def generate_text(model, start_string):
  # Evaluation step (generating text using the learned model)

  # Number of characters to generate
  num_generate = 1000

  # Converting our start string to numbers (vectorizing)
  input_eval = [mapping[s] for s in start_string]
  input_eval = tf.expand_dims(input_eval, 0)

  # Empty string to store our results
  text_generated = []

  # Low temperatures results in more predictable text.
  # Higher temperatures results in more surprising text.
  # Experiment to find the best setting.
  temperature = 1.0

  # Here batch size == 1
  model.reset_states()
  for i in range(num_generate):
      predictions = model(input_eval)
      # remove the batch dimension
      predictions = tf.squeeze(predictions, 0)

      # using a categorical distribution to predict the word returned by the model
      predictions = predictions / temperature
      predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()

      # We pass the predicted word as the next input to the model
      # along with the previous hidden state
      input_eval = tf.expand_dims([predicted_id], 0)

      text_generated.append(char_arr[predicted_id])

  return (start_string + ''.join(text_generated))

In [58]:
print(generate_text(model, start_string=u"Classius: "))

Classius: most sweet is loss of
himself aiming to be witness bone.
CAMILLO:
Why speak?

LUCIO:
I'll go and well!
I wis; and we will honour him;
You are about, not for my butt: let's sooner place. Beat which
Two late crown'd his head borne a father;
Or he mock'd as many yields and what you look
Should be interrest to enjoying 'Let's so;
We will perform your grace my husband.

BALTHASAR:
Then? O noble Rum!

ROMEO:
Nur, by my friends; and so, even there any offence for as liberty.

PRINCE EDWARD:
Inter true, or two be else of love
Am load forsook me, how do you love my hand.

RICHARD:
I cannot speak
So well to convenience and make an art
Which to we twice any money? a gentlenom ere he comes.
Now, if you with some fatal bed:
This music good and mine, only lamentation!
Alas! poor cass, when one desperately in good Capibon.
But, now on king Kate; and well nought him; he is an France and Lancaster
his foundawainities are dead. Or your opinion, hearing of
your honour untimely lay it in this
mi